name: Tagging

on:
  push:
    branches:
      - main

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      
      - name: Increment tag
        id: increment_tag
        run: |
          version=${{ env.latest_tag }}
          IFS='.' read -r -a parts <<< "$version"
          parts[2]=$((parts[2]+1)) # Increment the patch version
          new_tag="${parts[0]}.${parts[1]}.${parts[2]}"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
      
      - name: Create new tag
        run: |
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
